# Generated by Django 5.0.1 on 2025-08-03 11:31

import django.db.models.deletion
import django.utils.timezone
import propylon_document_manager.utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="cas_url",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fileversion",
            name="file",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to="files/",
                validators=[propylon_document_manager.utils.validators.validate_file_extension],
            ),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="file_extension",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="url",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fileversion",
            name="file_name",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="fileversion",
            name="version_number",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
