# Generated by Django 5.0.1 on 2025-08-05 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0002_fileversion_cas_url_fileversion_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileShare",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("can_edit", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_version",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="file_versions.fileversion"),
                ),
                (
                    "shared_with",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "unique_together": {("file_version", "shared_with")},
            },
        ),
    ]
